/**
 * Files and attachments.
 *
 * Mirrors src/db/migrations/0013_attachments.sql.
 *
 * Two types where one might be expected, for the same reason the schema has two
 * tables: a `File` is a stored blob, an `Attachment` is a link from that blob to
 * a record. The same signed contract hangs off a deal, an account and a service
 * job without three copies of the bytes existing.
 */

import type { Id, BigIntString, Sha256Digest } from './scalars.js';
import type { ActorKind, CrmEntity } from './enums.js';
import type { OrganizationId, UserId } from './entities.js';

// ---------------------------------------------------------------------------
// Enums — mirrors of the database types
// ---------------------------------------------------------------------------

export const FileUploadState = {
  /** Row exists and a storage key is reserved; the bytes are not confirmed. */
  Pending: 'pending',
  /** Bytes confirmed present, size and checksum recorded. */
  Stored: 'stored',
  /** Abandoned or superseded by a duplicate. The sweeper may delete the object. */
  Failed: 'failed',
} as const;
export type FileUploadState =
  (typeof FileUploadState)[keyof typeof FileUploadState];

export const FileScanStatus = {
  /** Not yet scanned. Downloads are refused — the gate fails closed. */
  Pending: 'pending',
  Clean: 'clean',
  Infected: 'infected',
  /** Trusted internal generation. A deliberate choice, never a default. */
  Skipped: 'skipped',
} as const;
export type FileScanStatus =
  (typeof FileScanStatus)[keyof typeof FileScanStatus];

export const AttachmentRole = {
  /** The ordinary case: a document on a record. */
  Attachment: 'attachment',
  Avatar: 'avatar',
  Logo: 'logo',
  /** The CSV a batch of records came from. */
  ImportSource: 'import_source',
  /** Produced by the system or an agent rather than uploaded. */
  Generated: 'generated',
} as const;
export type AttachmentRole =
  (typeof AttachmentRole)[keyof typeof AttachmentRole];

/**
 * Roles a record may hold at most once, enforced by a partial unique index.
 * A second avatar is an ambiguity the reader has to resolve, so the database
 * resolves it first.
 */
export const SINGLETON_ATTACHMENT_ROLES: readonly AttachmentRole[] = [
  AttachmentRole.Avatar,
  AttachmentRole.Logo,
];

export function isSingletonRole(role: AttachmentRole): boolean {
  return SINGLETON_ATTACHMENT_ROLES.includes(role);
}

// ---------------------------------------------------------------------------
// Identifiers
// ---------------------------------------------------------------------------

export type FileId = Id<'File'>;
export type AttachmentId = Id<'Attachment'>;

// ---------------------------------------------------------------------------
// Entities
// ---------------------------------------------------------------------------

/**
 * A stored blob. The bytes live in object storage; this row is the index and
 * the authorisation decision, not the filesystem.
 */
export interface File {
  readonly id: FileId;
  readonly organization_id: OrganizationId;

  readonly storage_bucket: string;
  /**
   * Generated by the database as `<organization_id>/<id>` and not writable.
   *
   * There is deliberately no way to supply one. A client-chosen key is a
   * tenant-isolation hole that no policy on this table can close, because the
   * breach happens in the object store rather than in Postgres.
   */
  readonly storage_key: string;

  readonly original_filename: string;
  /** Bare `type/subtype`. Parameters belong to the response header. */
  readonly mime_type: string;

  /** Null until the upload completes. `bigint`, so a string. */
  readonly byte_size: BigIntString | null;
  /** Null until the upload completes. Exactly 32 bytes. */
  readonly checksum_sha256: Sha256Digest | null;

  readonly upload_state: FileUploadState;
  readonly uploaded_at: Date | null;
  /** Set when this upload lost a deduplication race; points at the winner. */
  readonly superseded_by: FileId | null;

  readonly scan_status: FileScanStatus;
  readonly scanned_at: Date | null;
  readonly scan_detail: string | null;

  /**
   * Live attachments pointing at this blob, maintained by trigger. Recomputed
   * rather than incremented, so it cannot drift out of step with the rows.
   */
  readonly attachment_count: number;

  readonly uploaded_by: UserId | null;
  readonly uploader_type: ActorKind;
  /** Required by CHECK when uploader_type is 'agent'. */
  readonly uploader_agent: string | null;

  readonly created_at: Date;
  readonly updated_at: Date;
  readonly deleted_at: Date | null;
}

/**
 * A link from a blob to a record.
 *
 * `entity_type` + `entity_id` is polymorphic and carries no foreign key, but
 * unlike `activities` it is validated on write: attachments are low-volume and
 * long-lived, and a dangling one is discovered at the worst possible moment.
 */
export interface Attachment {
  readonly id: AttachmentId;
  readonly organization_id: OrganizationId;
  readonly file_id: FileId;
  readonly entity_type: CrmEntity;
  readonly entity_id: string;
  readonly role: AttachmentRole;
  readonly label: string | null;
  /** `numeric` so rows can be reordered without renumbering their neighbours. */
  readonly sort_order: number;
  readonly attached_by: UserId | null;
  readonly actor_type: ActorKind;
  /** Required by CHECK when actor_type is 'agent'. */
  readonly actor_agent: string | null;
  readonly created_at: Date;
  readonly updated_at: Date;
  readonly deleted_at: Date | null;
}

// ---------------------------------------------------------------------------
// The upload lifecycle
// ---------------------------------------------------------------------------

/**
 * Result of `app.begin_file_upload()` — where to put the bytes.
 *
 * When `already_stored` is true the content is already held and there is
 * nothing to upload: issue no presigned URL and attach `file_id` directly.
 */
export interface FileUploadTicket {
  readonly file_id: FileId;
  readonly storage_bucket: string;
  readonly storage_key: string;
  readonly already_stored: boolean;
}

export interface BeginFileUploadArgs {
  organization_id: OrganizationId;
  storage_bucket: string;
  original_filename: string;
  mime_type: string;
  /**
   * Supply when the client hashed the file before uploading. Content already
   * held by this organization is then returned without a second upload, and
   * content previously found to be infected is refused outright — renaming a
   * blocked file changes nothing, because the content is the identity.
   */
  checksum_sha256?: Sha256Digest | null;
  uploaded_by?: UserId | null;
}

/**
 * Arguments to `app.complete_file_upload()`.
 *
 * It returns the id of the *canonical* blob, which is not always the id passed
 * in: two uploads of identical content can be in flight at once, and the loser
 * is marked superseded rather than left as a second copy. Callers must use the
 * returned id from that point on.
 */
export interface CompleteFileUploadArgs {
  file_id: FileId;
  byte_size: BigIntString | number;
  checksum_sha256: Sha256Digest;
}

/**
 * Result of `app.can_download(file_id)`.
 *
 * Shaped like SendVerdict, and for the same reason: a caller that only gets
 * `false` has nothing to show the user and nothing to log.
 *
 * This answers content safety only. Tenant isolation comes from RLS on the read
 * inside the function; whether *this* user may see *this* record is the
 * caller's question.
 */
export interface DownloadVerdict {
  readonly allowed: boolean;
  /**
   * On deny: `file_not_found`, `file_deleted`, `upload_pending`,
   * `upload_failed`, `malware_detected`, or `scan_pending`.
   * On allow: `ok`.
   */
  readonly reason: string;
}

/** A row from `app.sweepable_files()` — a blob whose bytes can be removed. */
export interface SweepableFile {
  readonly file_id: FileId;
  readonly storage_bucket: string;
  readonly storage_key: string;
  readonly byte_size: BigIntString | null;
  readonly reason: SweepReason;
}

export const SweepReason = {
  /** Lost a deduplication race; the winner holds identical bytes. */
  SupersededDuplicate: 'superseded_duplicate',
  FailedUpload: 'failed_upload',
  /** Reserved but never completed. */
  AbandonedUpload: 'abandoned_upload',
  Deleted: 'deleted',
  /**
   * Stored, never attached, past the grace period. A policy choice rather than
   * a fact — act on this one deliberately.
   */
  NeverAttached: 'never_attached',
} as const;
export type SweepReason = (typeof SweepReason)[keyof typeof SweepReason];

// ---------------------------------------------------------------------------
// Insert shapes
// ---------------------------------------------------------------------------

/**
 * Direct insert into `attachments`.
 *
 * Prefer `app.attach_file()`: it resolves the organization from the file,
 * records agent attribution, and writes the `file_attached` timeline entry. A
 * caller assembling this by hand has to remember all three.
 */
export interface AttachmentInsert {
  organization_id: OrganizationId;
  file_id: FileId;
  entity_type: CrmEntity;
  entity_id: string;
  role?: AttachmentRole;
  label?: string | null;
  sort_order?: number;
  attached_by?: UserId | null;
}

/** Arguments to `app.attach_file()`. */
export interface AttachFileArgs {
  file_id: FileId;
  entity_type: CrmEntity;
  entity_id: string;
  role?: AttachmentRole;
  label?: string | null;
}

/**
 * Every database enum introduced by 0013, for the drift check in verify.ts.
 * A new enum added to a migration but not registered here is invisible to that
 * check, which is the failure mode the check exists to prevent.
 */
export const ATTACHMENT_DATABASE_ENUMS = {
  file_upload_state: FileUploadState,
  file_scan_status: FileScanStatus,
  attachment_role: AttachmentRole,
} as const;
